### ISSUE TITLE
贊助商頁面

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#108]

**Comment by yhsiang** [comment]
@othree can help draft sponsor page ?

**Comment by othree** [comment]
Where can I get data and logos

**Comment by yhsiang** [comment]
合作單位
- 財團法人開放文化基金會
- 中央研究院資訊科學研究所

共力夥伴
- 新竹物流

贊助單位
- 祐生基金會
- voxe.org #111 

logo 跟 資料待補上

**Comment by othree** [comment]
問一下現在每頁最下面的那個區塊
也是要全部顯示嗎？

**Comment by othree** [comment]
目前圖片還缺
- OCF
- 中央研究院資訊科學研究所
- 祐生基金會

**Comment by yhsiang** [comment]
OCF
![ocf-logo-640x156](https://cloud.githubusercontent.com/assets/93509/13672647/b758e3a0-e710-11e5-8c63-1b2c49525b7d.png)

**Comment by yhsiang** [comment]
@othree 每頁最下方只要顯示 logo ，然後再 Sponsor 頁面會按照贊助等級排序
可以先放，如果順序不對在調整

2014 的範例
- 每頁下方
  <img width="877" alt="2016-03-10 10 39 20" src="https://cloud.githubusercontent.com/assets/93509/13672745/02d4457c-e711-11e5-9d4e-55ece450221d.png">
- 贊助商頁面
  <img width="1227" alt="2016-03-10 10 38 58" src="https://cloud.githubusercontent.com/assets/93509/13672757/0ef7f52e-e711-11e5-9e3f-d177ba124206.png">

**Comment by othree** [comment]
- 中央研究院資訊科學研究所
- 祐生基金會

這兩個先從 SITCON 那邊找到圖片了

http://sitcon.org/2015/#/Sponsor

**Comment by othree** [comment]
#132 completed this issue
