### ISSUE TITLE
交通頁面

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#109]

**Comment by zbryikt** [comment]
transportation added, need to verify its content.

**Comment by clkao** [comment]
it feels weird everything is centered

**Comment by hlb** [comment]
@clkao 這邊不知道希望做什麼，需要設計稿

**Comment by clkao** [comment]
目前只是覺得資訊量不多卻超過一頁、置中有點難閱讀。

如果地圖小一點變成在右邊，說明文字置左左邊呢？（mobile 時就先文字後地圖）

**Comment by hlb** [comment]
@clkao 在 mobile device 上，目前地圖在前，文字在後。再看有沒有具體的設計稿吧 :)
