### ISSUE TITLE
更新「講者贊助」：Voxe.org

### ISSUE THREAD

**Issue by ghost** [g0v/summit2016#111]
link: http://voxe.org/welcome

簡介:

At <a href="http://voxe.org/">Voxe.org</a>, we believe in the power of technology to improve civic engagement and take the power back on politics. We believe in the power of social innovation to help forge an informed electorate. Back to 2012, we build a comparison tool for candidates’ platforms for elections. Simple, neutral and crowdsourced. <a href="http://voxe.org/">Voxe.org</a> is now settled in 16 countries and has reached out more than 3,5 million users. As one of the France Google Impact Challenge winner, we’re now working on a mobile app to improve civic engagement and increase our impact on policy : the Newswatch. A civic engagement mobile app based on political news with 3 steps : Information. Position. Action.
<a href="http://voxe.org/">Voxe.org</a>’s team recently launched <a href="happydemocracy.com ">happydemocracy.com</a>. The civic tech media, to bring civic tech events and news to the public.

**Comment by ghost** [comment]
![logo_voxe_240x120](https://cloud.githubusercontent.com/assets/3395905/13554214/23a94e82-e3dd-11e5-9957-ea059c55ec0b.jpg)

**Comment by othree** [comment]
請問有透明背景的版本嗎

**Comment by othree** [comment]
更新，目前先用白底做

**Comment by othree** [comment]
#132 completed this issue
