### ISSUE TITLE
Lightbox sizing

### ISSUE THREAD

**Issue by othree** [g0v/summit2016#115]
Current lightbox will expand to outside of visible region.
We should have a max w/h and scrollable content.

**Comment by jackycute** [comment]
I would like to help, but I don't see it expand out of bound.

**Comment by othree** [comment]
I have a simple solution already complete.
A PR is coming :)

You can help let it become better on mobile view.
I expect on mobile view, the lightbox become fullscreen.

And the very long talk is "Open Source Digital Platform for Bridging the Gap between Citizens and Local Government in Nepal"

**Comment by jackycute** [comment]
:+1:

**Comment by yhsiang** [comment]
Use new style now, no need to do this anymore
