### ISSUE TITLE
贊助商頁面：合作夥伴-琅茶

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#127]
琅茶立志將台灣茶細膩之美，傳遞給全世界！每季親訪產地，嚴選上質茶園在最適天氣時辰，由優秀茶師採製的「單品茶」(Single Origin)，詳載茶事，與時俱進，售完不再，真正感受每片山林「此刻此地・獨一無二」的純粹美好。一起品遍千變萬化的台灣茶吧！開展好茶地圖，認識自己的味蕾，找到屬於你「琅琅上口」的好茶。

Wolf Tea believes Taiwan has the best tea in the world because of the climate and great tea makers. Each of our offering is a selected single-day-harvest, single-batch-creation which is superior and unique in flavour. We want to share the ever-changing experience of tea tasting, and carefully evaluate each sip. In a way, each taste of tea is “one chance in a lifetime” beautiful experience.

![wolftea_logo](https://cloud.githubusercontent.com/assets/8463261/13641401/394f7c34-e653-11e5-9df2-9466c253cfe2.png)

logo 高度統一120px

**Comment by beichou** [comment]
link: www.wolftea.com

**Comment by othree** [comment]
順便確認一下現在有幾種類別
#108 只有三種
合作夥伴是另外的嗎？

**Comment by beichou** [comment]
現有4種：
合作單位
共力夥伴
贊助單位
合作夥伴

**Comment by othree** [comment]
有沒有比較正確的英文翻譯呢？
方便給元件 id

**Comment by yhsiang** [comment]
合作單位 Co-Organizer
共力夥伴 Special Thanks (本來想 Co-Partner 感覺很怪 XD)
贊助單位 Sponsor
合作夥伴 Partner

**Comment by othree** [comment]
#132 completed this issue
