### ISSUE TITLE
贊助商頁面：共力夥伴-新竹物流＆財團法人RC文化藝術基金會

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#128]
![-01](https://cloud.githubusercontent.com/assets/8463261/13641917/5b9085b6-e655-11e5-816a-e1d28f7b81f4.png)

![rc _20160304_143313](https://cloud.githubusercontent.com/assets/8463261/13641846/10008a60-e655-11e5-9919-4d92b918a9b9.jpg)

logo高 120px

**Comment by othree** [comment]
他們實際上是同一間吧（大頭一樣），這樣要放兩個 logo? (版面會是別人的兩倍)

**Comment by beichou** [comment]
他們是支持Evangelist Level的「共力夥伴」，再麻煩「新竹物流」＆「財團法人RC文化藝術基金」兩個logo都放置上去。感謝！

**Comment by othree** [comment]
財團法人RC文化藝術基金會有網址嗎？

**Comment by beichou** [comment]
這個比較特別，只會有logo，不用放簡介跟網址。

**Comment by othree** [comment]
RC 的 logo 左右沒有置中，我直接調整了喔（其實影像品質也有點差）

**Comment by othree** [comment]
#132 almost completed this issue, forget to deal with RC's link issue
