### ISSUE TITLE
Different JSON-LD at different page

### ISSUE THREAD

**Issue by othree** [g0v/summit2016#130]
Save network bandwidth.
And more specific data information to different url.

**Comment by MrOrz** [comment]
I have a work-in-progress that supports different title & og:image for each page when prerendering.
Maybe I can integrate json-ld into this as well!

**Comment by othree** [comment]
@MrOrz , Great, I have looked your code. And it should be ok to do :smile:

**Comment by othree** [comment]
- home
  - basic info
  - offer
- schedule
  - basic info
  - subevents
- sponsors
  - basic info
  - ! no sponsors relation can be use now, still looking
