### ISSUE TITLE
Cleanup unused assets

### ISSUE THREAD

**Issue by othree** [g0v/summit2016#136]
Lots of outdated file could be clean.
https://github.com/g0v/summit.g0v.tw/tree/gh-pages/2016

**Comment by MrOrz** [comment]
Got it. I'll try adding `--delete` to rsync.

https://github.com/g0v/summit.g0v.tw/blob/2016/deploy#L21

**Comment by MrOrz** [comment]
`app/images/speakers2014` can be safely removed, right?
It seems to be used in some react components that is no longer used.

**Comment by MrOrz** [comment]
Implemented in https://github.com/g0v/summit.g0v.tw/commit/88ea8ee3ac7094c5867c73efc1f2259c1f649dcb
