### ISSUE TITLE
贊助單位-均一教育平台

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#159]
![mesh_logo_black_text](https://cloud.githubusercontent.com/assets/8463261/14012085/68b264be-f1de-11e5-98da-18679ae630c2.png)

中文的免費均等一流教育
均一教育平台是由財團法人誠致教育基金會創辦。我們的目標是透過雲端平台提供免費的『均等、一流』的教育機會給每一個人。

任何人都可以使用網站所有的資源。不管你是學生、老師、自學家庭、校長、二十年後想回去當學生的大人、或是對地球生物好奇的友善外星人，均一的課程內容與資源完全免費提供使用。

link: http://www.junyiacademy.org

**Comment by othree** [comment]
No en desc? or not required

**Comment by beichou** [comment]
應該不會有英文介紹

**Comment by othree** [comment]
那英文頁面要放中文還是不放

**Comment by beichou** [comment]
英文頁面不放，謝謝。
