### ISSUE TITLE
improve mobile view for sponsor page

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#160]
Make the description text folded by default? or make it in lightbox in mobile view

<img width="392" alt="screen shot 2016-03-24 at 7 08 44 pm" src="https://cloud.githubusercontent.com/assets/69736/14015435/e464f346-f1f3-11e5-8841-19eaadc52cd0.png">

**Comment by jackycute** [comment]
Try to fix in 93c93efa81dc703f4b98848d249be835cb28b768

**Comment by clkao** [comment]
@jackycute++
