### ISSUE TITLE
合作單位-KKTIX

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#162]
輕鬆流暢的活動管理體驗
每次舉辦活動的時候，都在煩惱怎麼製作網頁、處理報名事宜嗎?
KKTIX滿足您舉辦活動的各項需求，從建立、管理、行銷到售票，一切都在彈指之間完成。

Smooth Event Management Experience
Want to get things done efficiently when organizing events? KKTIX keeps everything in just few clicks from creating page, event management, marketing, to selling tickets, all in one place.

link: http://kktix.com

![kktix](https://cloud.githubusercontent.com/assets/8463261/14059541/7439570a-f37f-11e5-809a-2c66e352e872.jpg)

**Comment by othree** [comment]
有兩倍大的圖嗎？
現在其實都有做 2x 顯示器支援
實際上是 480 \* 240

**Comment by othree** [comment]
Any update?

**Comment by yhsiang** [comment]
@othree 直接先換上去吧，跟贊助商要圖片也是要一陣子的

**Comment by beichou** [comment]
取得新檔案後會再上傳，麻煩先更新了，感謝。

**Comment by beichou** [comment]
kktix_logo_ 480 \* 240

![kktix_logo_ 480x240](https://cloud.githubusercontent.com/assets/8463261/14109260/b930690e-f5f3-11e5-9196-b326f1b985d2.jpg)

**Comment by othree** [comment]
這張好像垂直沒置中，我有處理了一下
你再確認一下他們是不是故意的（第一張看起來沒這個問題）

**Comment by beichou** [comment]
感謝幫忙置中！
