### ISSUE TITLE
每一個 talk 的 permalink

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#165]

**Comment by othree** [comment]
Have link but not functional now.

**Comment by hsin421** [comment]
剛入坑 可以再說明深入些這個issue要什麼嗎 XD

**Comment by ipaaa** [comment]
就是在議程表中點入特定演講時，可以直接連到那一頁（方便轉貼）
http://summit.g0v.tw/2016/schedules#day1-all-4 例如點這個，就要維持介紹頁 pop-up 出來
<img width="1135" alt="screen shot 2016-03-31 at 21 06 29" src="https://cloud.githubusercontent.com/assets/2939042/14176629/871bac0c-f784-11e5-92a6-b731ce64fe55.png">

但現在轉貼url會回到議程頁......

**Comment by hsin421** [comment]
https://github.com/g0v/summit.g0v.tw/pull/193
