### ISSUE TITLE
贊助單位 - 天氣風險

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#170]
![footer-w](https://cloud.githubusercontent.com/assets/69736/14140947/9bbf9c80-f6ae-11e5-864b-dbba92bec2f2.png)

天氣風險管理開發公司

WeatherRisk，天氣風險管理開發，是台灣唯一利用氣象資料創業的公司，配合專業知識與經驗，長時間經營取得多張個人與團體氣象及海象預報證照。雖處資源有限的新創環境，仍將服務深入各行業，客戶包括超過300家國內外企業與公家單位。透過氣象數據的處理、開源程式的應用及視覺設計的加值，提供各類氣象相關問題的解決方案。面對氣候變遷下的極端天氣日益增多，以社會企業的理念，希望由資料服務保障大眾降低風險。

**Comment by othree** [comment]
是 https://www.weatherrisk.com/ 嗎？

**Comment by othree** [comment]
https://github.com/g0v/summit.g0v.tw/pull/176
Still need 2x logo(480 x 240)

**Comment by othree** [comment]
還是需要 2x 大小的 logo
不然 HiDPR 裝置看起來會鋸齒很明顯

**Comment by beichou** [comment]
logo更新 
![logo back_0401](https://cloud.githubusercontent.com/assets/8463261/14203234/622d76fe-f82f-11e5-99e5-c6e47d1501af.png)

**Comment by beichou** [comment]
## 中文簡介更新

WeatherRisk，天氣風險管理開發，是台灣唯一利用氣象資料創業的公司，配合專業知識與經驗，長時間經營取得多張個人與團體氣象及海象預報證照。雖處資源有限的新創環境，仍將服務深入各行業，客戶包括超過300家國內外企業與公家單位。服務類別分為七大類別，包含氣象數據服務、氣象多媒體服務、天氣預報及氣候評估、防災應變整合、天氣保險、營運持續管理及科普教育和科學推廣。透過氣象數據的處理、開源程式的應用及視覺設計的加值，提供各類氣象相關問題的解決方案。面對氣候變遷下的極端天氣日益增多，以社會企業的理念，希望由資料服務保障大眾降低風險。
