### ISSUE TITLE
主持人資訊

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#172]
主持人跟在大標下面

動力：蔡淑芳
地基：clkao
骨架：李怡志
藍圖：au
配線：林祖儀
鷹架：衷嵐焜
監工：劉致昕
廣場：吳銘軒
空調：Jimmy

D2 下午全場：李雪莉

**Comment by yutin1987** [comment]
D2下午全場 是指 
Consul - 西班牙的開放政府平台與數位民主革命 後嗎？

**Comment by clkao** [comment]
@yutin1987 yes
