### ISSUE TITLE
贊助商：網絡行動科技

### ISSUE THREAD

**Issue by ghost** [g0v/summit2016#183]
先放 2014 年的

link: http://netivism.com.tw/

logo: http://summit.g0v.tw/2014/images/sponsor/netivism.png

**Comment by othree** [comment]
Any description?

**Comment by ghost** [comment]
先放 2014 的敘述，感謝！如下：

NETivism
網絡行動科技（NETivism）自許為從數位公益出發的社會企業，多年來專注為非營利組織提供以自由軟體為基礎的資訊科技應用解決方案。 我們認為網路資訊科技能夠促成社會變革，影響文化、政治、環境等公共議題，帶來娛樂與商業行為之外的改變。非營利組織工作者可以在我們以及其他有志於此的公司和社群的努力下，善用網際網路深化社會各種的力量，激勵人們採取行動，創造出更好的社會。

**Comment by othree** [comment]
#184 

Still need the 2x logo image

**Comment by ghost** [comment]
不好意思，忘了說明「網絡行動科技」的順序在「天氣風險」的後面 QQ

再麻煩了，謝謝～～

**Comment by rainyday309** [comment]
#186 
加了2X logo image
位置移到weather-risk後面
但沒有英文的description
第一次參與請多包涵

**Comment by othree** [comment]
圖片看起來鋸尺蠻嚴重的
有原始檔嗎？

https://github.com/rainyday309/summit.g0v.tw/blob/1d224312c36257fc8b7c25ce6927a0ed5ef6dcf2/app/images/sponsors/netivism.png

**Comment by rainyday309** [comment]
用2014的logo放大的，原始檔就是soidid最上面提供的那一個

**Comment by othree** [comment]
接洽窗口有要去要新的嗎，手動放大其實沒用

**Comment by rainyday309** [comment]
![netivism](https://cloud.githubusercontent.com/assets/7822270/14198047/8502e2ee-f808-11e5-9b45-6769594273b0.png)

再處理了一次，這樣子夠嗎？

**Comment by ghost** [comment]
我會再去跟贊助商要大一點的圖～

**Comment by ghost** [comment]
更新介紹文案

中文：
網絡行動科技（NETivism）自許為從數位公益出發的社會企業，七年來專注為非營利組織提供以自由軟體為基礎的資訊科技應用解決方案。 我們認為網路資訊科技能夠促成社會變革，影響文化、政治、環境等公共議題，帶來娛樂與商業行為之外的改變。目前提供 netiCRM.tw 支持者關係管理雲端服務，協助非營利組織滿足定期定額線上捐款自動化、電子報行銷、活動報名等需求。

英文：
NETivism (Internet for Activism) is a social enterprise focus on solving digital divide for Non-Profit Organization, via Open Source solution(Drupal & CiviCRM) and Love.

**Comment by othree** [comment]
@rainyday309 有比較好了，不過其實中文字的地方還是有些怪怪，也是可以先暫用，通常是不會自己放大圖片啦，因為放大只會失真

@soidid 收到

**Comment by ghost** [comment]
來了～

![netivism_logo_480x240_ppi300](https://cloud.githubusercontent.com/assets/3395905/14202816/be49357a-f82c-11e5-9358-3a26bdd64efd.png)
