### ISSUE TITLE
 加「最新消息」頁

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#189]
<img width="747" alt="screen shot 2016-03-31 at 21 01 01" src="https://cloud.githubusercontent.com/assets/2939042/14176473/c1579cc4-f783-11e5-8a06-532ec6110229.png">
看是要 
1) 變成能夠貼文（轉貼fb議程介紹） or 
2) 連到這一頁  http://blog.g0v.tw/categories/g0v-Summit

**Comment by bobby1030** [comment]
進到 #g0vsummit16 這個 Hashtag 應該也可以
https://www.facebook.com/hashtag/g0vsummit16
