### ISSUE TITLE
加合辦單位 logo：開放文化基金會

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#19]
![screen shot 2014-09-24 at 19 00 56](https://cloud.githubusercontent.com/assets/2939042/4387227/5eac2814-43da-11e4-8642-878f675e86c4.png)

ai 檔案在這，需要裁成上方這樣
https://drive.google.com/?usp=docs_home&authuser=0#folders/0BzGJ4qvz2D3ENHZJXzBZQ3dMSzQ

**Comment by marygeek** [comment]
我新增了，但陷入merge和deploy地獄中，網站就是顯示不出來

**Comment by ipaaa** [comment]
已經出來咧，mary 大爆發～ 社會所論壇也加了 \o/
