### ISSUE TITLE
贊助單位-CLBC

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#192]
clbc位置於祐生後面，均一前方。
＝＝＝＝＝＝
中文版：

CLBC 為台灣最大的工作空間,我們很可以理解創業本身的艱 難困苦,經營空間本身是一件辛苦但卻有趣的事情,辛苦自然 不在話下,但棒的是許多團隊來到這裡, 並在這空間裡合作創造出來許多故事,CLBC不僅只是一個工作 的地方,更像創業團隊的大家庭,在這發生了許許多多的故 事,也等著你、我一同來共創下一個故事。

英文版：

As the biggest Coworking Space in Taiwan, CLBC understands the struggles of starting up business. Establishing a coworking space was indeed not an easy task, though it was a fun process to witness all the stories that had been made here! CLBC is not only a space for work, but more of a big family to startups. So, what are you waiting for? Let’s join in to build up more and more stories with us!

link to http://clbc.tw

![clbc-01](https://cloud.githubusercontent.com/assets/8463261/14180147/5fa5c4e0-f794-11e5-8947-1f185fe0519d.jpg)

**Comment by othree** [comment]
先借問一下，目前的順序是正確的了嗎？

**Comment by beichou** [comment]
目前順序是正確的。
