### ISSUE TITLE
link schedule sessions to speakers

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#195]
1. use speaker_key if speaker name is localized already
2. remove bio from schedule session json, as data can now be pulled from speakers.json

**Comment by yhsiang** [comment]
@ChenYoyo, Could you help to do this, look like the solution in landing page.

I think also related to #252

**Comment by ChenYoyo** [comment]
@yhsiang  你的意思是把landing page,議程的Session功能放進去講者頁面嗎？

**Comment by yhsiang** [comment]
yes, 但是講者可能要變成 一行三個，並且跟議程一樣，Session 跳出來的時候，講者要能往左 Shift
