### ISSUE TITLE
議程 layout 調整

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#20]
因為還要新增 unconf 說明、議程簡介英文也未放
希望把目前塞在「議程表」裡的簡介拉到上方，另成一區「議程簡介」，簡易 mockup 入下：
https://moqups.com/ipa/Wp6ggfn8/

**Comment by clkao** [comment]
要修改前請先 sync, 因為 schedule.jade 已經改成用 json 的資料囉

**Comment by ipaaa** [comment]
歐 議程內容要去 i18n/src/zh-tw/schedule.ls 改？

**Comment by clkao** [comment]
es, @zbryikt 正在把中英文版本合併成一個檔案，可以等他先弄完，或者跟他說要改什麼

**Comment by ipaaa** [comment]
@zbryikt @marygeek 這個可以幫忙改一下嗎？@@
希望可以把說明文拉到上面（像上面 mockup 所示，這邊也再貼）：
https://moqups.com/ipa/Wp6ggfn8/

10/1前希望有更完整議程說明，因為有人說蠻有門檻，需要更多導言

**Comment by zbryikt** [comment]
應該不難改, 不過這幾天在趕 E 論壇的專題, 要擠點時間出來

**Comment by zbryikt** [comment]
剛剛想了一下, 這件事放在 json 裡好像有點不太對, 應該要類似 g0v.tw md 的做法比較好?
而且感覺直接用 html 就好, 這樣的話就相對簡單, 先參考這個 dev/session/layout branch: 9a381dfad4be1c25021d6ba56c580d1c9893b136 
在 schedule.jade 裡判斷語言來讀位於 app/content/(lang)/ 的另一個 jade
這樣的話 ipa 會改嗎？

**Comment by ipaaa** [comment]
是 jade md 的話我都可以！

**Comment by shelling** [comment]
放在 json 應該也是有可能的，每個 session 用 key 命名，內有中英文內容。比方說

```
{ session_shelling:
    { en:
        {
            title: <English Title>
        }
    }
    { zh: 
        {
        title: <Chinese Title>
        }
    }
}
```

參考看看

Update:
回覆才發現 ipa 已經回了，那就沒關係了 XD

**Comment by zbryikt** [comment]
我一開始有試著用 json, 不過 mockup 中的需求是文字的簡單排版, 段落數量看起來也可能會變化
比起排版複雜的時程表來說, 使用 json 的好處似乎就沒了
再加上使用變數 & mixin 這部分對 ipa, mary 負擔看起來比較重, 
很有可能會變成任何的修改都需要我來做, 
與其這樣不如另外弄個 jade  

@ipaaa 如果你覺得可以的話, 那就在  dev/session/layout 改改看?
現在基本上只要再把文字補進去就好了

**Comment by clkao** [comment]
@zbryikt 咦，可是 session intro 不是本來就已經在 json 裡了？ maybe allow the "get" mixin to get specific lang in addition to current one?

**Comment by zbryikt** [comment]
oops.. 我現在才發現是把原來的那四個主題介紹拿出來
所以需要的是像 f9cf0c6451b1d0 這樣嗎?

**Comment by zbryikt** [comment]
我重新整理了一下 dev/session/layout 的 schedule, 現在差不多就是 @ipaaa  mockup 的那樣, 看看合不合用?

**Comment by clkao** [comment]
@zbryikt++ can you use _() for the heading? (see gulpfile for manual update of the po templates and file)  also I think we should hide zh for the en-US version

**Comment by clkao** [comment]
改 lightbox 好了，請 @yhsiang  協助
