### ISSUE TITLE
贊助單位-均一教育平台footer名稱需變更

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#200]
贊助單位-均一教育平台名稱變更為 誠致教育基金會
只需修改 footer，贊助頁面不需修改

<img width="1247" alt="2016-04-01 4 35 27" src="https://cloud.githubusercontent.com/assets/8463261/14201982/e602ba5a-f827-11e5-9a61-4ed977d9c0e9.png">

**Comment by rainyday309** [comment]
您指的是修改圈起來的地方嗎
<img width="1247" alt="githubissue" src="https://cloud.githubusercontent.com/assets/7822270/14213110/c68e10b6-f868-11e5-8e9a-d9d34414d842.png">

**Comment by beichou** [comment]
是的。有辦法與贊助頁不同名稱嗎？還是一定需要兩邊同步呢？

**Comment by othree** [comment]
可以只是要改些 code

**Comment by beichou** [comment]
了解，那先不處理，待我詢問一下對方。感謝！

**Comment by othree** [comment]
收到，不過是不會太複雜（推測）

**Comment by clkao** [comment]
with an additional field like footer_name that overrides?
