### ISSUE TITLE
贊助單位：祐生研究基金會（logo+中英文簡介更新）

### ISSUE THREAD

**Issue by ghost** [g0v/summit2016#201]
祐生研究基金會由推動建築與環境永續發展之研究開始，推動長期的知識累積與人才培養。除了過去建築、環境、生態、健康與資訊社會與文化等面向之碩士論文獎助主題外，本會目前定期舉辦的聯誼會及讀書會，強化祐生成員的知識密度。其後，於 2011 年起，本會持續針對國內開源活動進行贊助，也針對國內獨立遊戲開發者，推動知識與資訊分享聚會，並贊助台灣開發者前往特定國際遊戲競賽，期能幫助國內相關社群之發展。

Since 1987, the Archilife Research Foundation started long-term researches in architecture, sustainability, and go on to other areas of knowledge integration. Efforts including previously giving scholarships in aforementioned areas, and currently holding reading group meetings and communion events for knowledge keepers to better our understandings of the world. Starting from 2011, we also have been sponsoring various open source related events, holding meetups and game jams for local game developers' community, and giving out scholarships to support indie game teams and encourage them to go to international game festivals.

![archilife_full_logo_480](https://cloud.githubusercontent.com/assets/3395905/14202454/a73f3228-f82a-11e5-97aa-622dd216d462.png)

**Comment by othree** [comment]
Logo 是哪裡不一樣啊，看不太出來

**Comment by ghost** [comment]
光看圖檔是邊邊切的比較貼近？可能放上去會字比較大一點？

**Comment by othree** [comment]
看起來他是貼齊邊邊了，圖片寬度剛好 480
可是貼齊邊邊這樣會有點醜喔
要再跟他們溝通一下嗎？
（還是要直接幫他們調整）

**Comment by ghost** [comment]
先更新簡介好了，logo 先維持不變（比較美）。
我再跟窗口溝通～
謝謝！

**Comment by othree** [comment]
是可以更大，只是不建議貼齊
再麻煩你跟他們說明一下
需要的話我可以貼齊給他們看看樣子

**Comment by ghost** [comment]
需要貼齊的樣子～謝謝！

**Comment by othree** [comment]
哈哈，下次 summit 看來要先設定好最小間距，希望他們不要又後悔XD

**Comment by pcchou** [comment]
@soidid 貼齊的話是長這樣唷
![443](https://cloud.githubusercontent.com/assets/5615415/14211488/021cafb8-f7f4-11e5-817c-ee982444d804.png)

**Comment by ghost** [comment]
@pcchen 可以先不換 logo（用原本沒有貼齊的），然後把簡介推上去嗎？
這樣可以讓窗口直接看網站確認。謝謝！

**Comment by pcchou** [comment]
簡介我已經推上去了！

**Comment by shelling** [comment]
@pcchen Looks like this is already done. I close it.
