### ISSUE TITLE
Nav bar at tablet width 

### ISSUE THREAD

**Issue by hsin421** [g0v/summit2016#212]
這是 @ width = 1004px
<img width="998" alt="screen shot 2016-04-02 at 6 28 04 pm" src="https://cloud.githubusercontent.com/assets/7806299/14229393/cbf57c5e-f900-11e5-8357-833bb6be3cfc.png">

**Comment by hsin421** [comment]
This is iPad (9.7). No hamburger menu.
![image](https://cloud.githubusercontent.com/assets/7806299/14231952/0d473e14-f964-11e5-9e51-79c5f8d4b6cb.png)

**Comment by shelling** [comment]
@hsin421 What's the physical version of your iPad. iPad Air?

**Comment by hsin421** [comment]
@shelling ipad 2, css width in landscape @ 1024px 
http://mydevice.io/devices/

**Comment by yhsiang** [comment]
@hsin421 Could you help to verify this?

**Comment by hsin421** [comment]
On Chrome simulator (iPad landscape) everything is good.

On my iPad 2 (landscape & protrait Safari) Nav bar looks fine, but does not work. Hamburg menu is not clickable. Languages can't be toggled. Very weird. It could be only my iPad. Please test it on other iPads too.

update:
Nav bar works in my iPad Chrome. Only breaks in iPad Safari.

**Comment by othree** [comment]
My iPad Air works fine (language toggle and menu)

**Comment by hsin421** [comment]
Ok my iPad Safari is bad XD. It works fine on my phone (safari) too.

No need to reopen I guess...
