### ISSUE TITLE
講者列表有g0v、g0v.tw兩種寫法，可考慮統整為一種

### ISSUE THREAD

**Issue by thebrecht** [g0v/summit2016#224]
http://summit.g0v.tw/2016/speakers 講者列表有g0v、g0v.tw兩種寫法，要不要考慮選擇其中一種?

**Comment by yhsiang** [comment]
PR welcome

**Comment by bobby1030** [comment]
已把 g0v.tw 全部 replace 成 g0v

**Comment by clkao** [comment]
closed by #229
