### ISSUE TITLE
贊助單位-Open Knowledge International 

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#227]
次序在Voxe.org後，中文版也請放英文簡介。

Open Knowledge is a worldwide non-profit network of people passionate about openness, using advocacy, technology and training to unlock information and enable people to work with it to create and share knowledge.

https://github.com/okfn/branding/blob/master/assets/standard-logo-rgb.svg

**Comment by pcchou** [comment]
我把圖片至中之後變這樣，已經發 pull request 了，麻煩再看看 :see_no_evil:：
![475](https://cloud.githubusercontent.com/assets/5615415/14392997/108029e6-fdf7-11e5-9370-485e703ca667.png)
