### ISSUE TITLE
議程 responsive

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#24]
窄的話會全部擠在一起

**Comment by clkao** [comment]
is there anything from the coscup agenda page we can steal?

**Comment by marygeek** [comment]
截圖一下，沒圖沒真相
我的安卓倚看是會切到但至少可以縮放
只有menu反而有高度問題
不過目前人在山上，用手機無法夾圖上來給大家看><

Chia-liang Kao notifications@github.com 於 2014年9月26日星期五寫道：

**Comment by darbychang** [comment]
用 table 要少一個 column 超難的啊, 其中還有 rowspan="2" 的東西...

**Comment by darbychang** [comment]
試著用 flexbox, 先放在 schedule_flex.jae, 讓大家討論看看
