### ISSUE TITLE
贊助單位：經濟民主連合 318 結餘款（logo+中文簡介）

### ISSUE THREAD

**Issue by ghost** [g0v/summit2016#249]
經濟民主連合，原名「反黑箱服貿民主陣線」，是由數十個台灣公民團體組成的社團聯盟。

組織名稱：

(中文) 經濟民主連合 318 結餘款
(英文) Economic Democracy Union - 318 Movement Fund

中文簡介：

> 經濟民主連合，原名「反黑箱服貿民主陣線」，是由數十個台灣公民團體組成的社團聯盟。
> 
> 在 2016 年 318 運動兩周年論壇，我們確立中期運動目標為：
> 一、 拒絕服貿、貨貿、亞投行；
> 二、 莫讓ＴＰＰ傷害台灣；
> 三、 拒絕「同屬一中」，捍衛台灣人民自決權；
> 四、 深化民主，推動七項立法：通過民間版監督條例，經貿條約締結應有專法或專章，因應貿易自由化支援調整條例要大修，立法規範中資，反媒體壟斷法應考量中國因素，制定基本工資專法與外國人在台工作專法：
> 五、繼續對抗兩岸權貴資本及國共政商集團。
> 
> 完整簡介：http://edutw2016.blogspot.tw/p/blog-page_7.html

![edu](https://cloud.githubusercontent.com/assets/3395905/14554916/5281b26c-0322-11e6-8386-08f27c4ce296.gif)

連結位置：https://www.facebook.com/%E7%B6%93%E6%BF%9F%E6%B0%91%E4%B8%BB%E9%80%A3%E5%90%88-593374924100942/timeline

**\* 目前沒有英文簡介，順序在微軟之後

**Comment by othree** [comment]
可以請他們輸出 png 或是直接給 480*240 的圖嗎？
gif resize 後效果不是很好
