### ISSUE TITLE
improve speaker page lightbox

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#252]
- [x] show localized bio
- [x] permalink

**Comment by yhsiang** [comment]
Now have http://summit.g0v.tw/2016/speakers#day1-all-8  but still not work 

consider about these codes to implement
https://github.com/g0v/summit.g0v.tw/blob/2016/app/javascripts/components/Schedule/index.jsx#L131-L143

**Comment by yhsiang** [comment]
Done but some bugs, open in #278
