### ISSUE TITLE
英文版的 Menu 太長

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#255]
@bobby1030 please help to solve this.

<img width="1261" alt="2016-04-17 8 21 15" src="https://cloud.githubusercontent.com/assets/93509/14586906/f7887e86-04d9-11e6-80dc-dcde7e3633ab.png">

**Comment by bobby1030** [comment]
好像除了把摺疊的限制拉低外，沒有其他解法了....
不過這樣又會造成視覺上很糟@@

**Comment by yhsiang** [comment]
中文跟 English 只要顯示一個就好了

英文版下面顯示 中文
中文顯示 English

**Comment by bobby1030** [comment]
這樣不太能解決，因為現在的 limit 是小於 930px 才會摺疊，
但大概小於 1100px 就會連現在 English 的地方一起蓋掉。
所以我現在打算 1200px （比圖再窄）就摺疊
![_011](https://cloud.githubusercontent.com/assets/10739091/14587123/9bd9a79e-04df-11e6-8a69-f9fd95c99ebf.png)

**Comment by yhsiang** [comment]
那就把最新消息 放到首頁 而不是放到 Menu

**Comment by bobby1030** [comment]
那我先發個 PR 把最新消息拔掉，改天再丟首頁...
