### ISSUE TITLE
unconf 資訊

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#259]

**Comment by yhsiang** [comment]
@alcho please help to provider information!

**Comment by yhsiang** [comment]
https://docs.google.com/document/d/1S9wCmNIbdD4-P5aIbuol2s34cEiYHFdSYd1PX4LpGto
最下面的
Unconf 規則與內容介紹

**Comment by yhsiang** [comment]
1. 獨立一頁 Unconf 頁面
2. 連結放在首頁 Milestone 不要放 Menu

**Comment by pm5** [comment]
現在才看到連結放 milestone 不放 menu，剛改好了。

Markdown 位置 https://github.com/g0v/summit.g0v.tw/tree/2016/app/text/unconf
