### ISSUE TITLE
雙講者在 speaker 頁面沒有 abstract

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#285]
@ChenYoyo, 
議程頁面有
http://summit.g0v.tw/2016/schedules#day1-all-34

但是講者頁面就消失了
http://summit.g0v.tw/2016/speakers#none-41

**Comment by ChenYoyo** [comment]
@yhsiang   我當初是想說speaker頁面，點擊單一講者卻跳出兩位講者介紹，這樣感覺怪怪的，所以就維持原本speaker頁面的只顯示一位講者的Biography，不過既然有需求我就把功能加進去~
