### ISSUE TITLE
支持單位-經濟部工業局 Industrial Development Bureau Ministry of Economic Affairs

### ISSUE THREAD

**Issue by beichou** [g0v/summit2016#297]
![-01](https://cloud.githubusercontent.com/assets/8463261/15141472/bc3fbbc2-16d2-11e6-8e50-6cd072446e66.jpg)

次序：Teradata 後，祐生前

簡介：
經濟部工業局於2013年11月起，啟動「開放資料產業應用推動計畫」，致力於推動產業應用政府開放資料，期望業者運用政府與企業開放資料開發新產品與服務，創新商業或服務模式，並協助民間連結政府機構，爭取政府資料集開放；本計畫委託台北市電腦公會執行( http://opendata.tca.org.tw )，計畫提供創新競賽、產業補助、行銷推廣與國際合作各項資源，歡迎國內業者與有志之士合作，共同建全國內資料應用環境。

link to: http://www.moeaidb.gov.tw

英文簡介後補，請先空白即可。

**Comment by pcchou** [comment]
Done. #298
![596](https://cloud.githubusercontent.com/assets/5615415/15142179/721359a6-16d6-11e6-8203-d73b477c48b8.png)
