### ISSUE TITLE
共筆連結放在最上面分頁或明顯處

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#307]
現在在很下方

**Comment by wildjcrt** [comment]
solved.
https://github.com/g0v/summit.g0v.tw/commit/ccdcbe6236558dd0efcd7f65f81f78e71c496b40

**Comment by ghost** [comment]
英文版的 milestone 沒改

{
        "title": "Shared Notes",
        "url": "http://beta.hackfoldr.org/g0v-summit-2016"
      },
      {
        "title": "R0 Simultaneous Interpreting",
        "url": "http://i.summit.g0v.tw:8000/r0"
      },
      {
        "title": "R1 Simultaneous Interpreting",
        "url": "http://i.summit.g0v.tw:8000/r1"
      },
      {
        "title": "R2 Simultaneous Interpreting",
        "url": "http://i.summit.g0v.tw:8000/r2"
      },
      {
        "title": "Live Streaming",
        "url": "http://summit.g0v.tw/2016/live"
      }
