### ISSUE TITLE
交通資訊部份加入接駁車資訊

### ISSUE THREAD

**Issue by choupi** [g0v/summit2016#31]
接駁車
11/8 7:30~9:15 在捷運南港展覽館站二號出口搭乘

shuttle bus
11/8 7:30~9:15 from Exit 2, MRT Taipei Nangang Exhibition Center Station

**Comment by marygeek** [comment]
已經更新commit

**Comment by clkao** [comment]
@marygeek: 下回可以在 commit message 中加註 "Closes #31" 這樣就會自動把這個 issue 關掉囉
