### ISSUE TITLE
add staff list

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#35]
https://trello.com/c/ik4TCsey

與手冊定稿同：

**Comment by ipaaa** [comment]
https://docs.google.com/spreadsheets/d/17YLORjohySePT1O02vFxOgzWedk1srcaXOJ-Wy7TEpg/edit#gid=588777545 @marygeek @zbryikt  這個要在年會前上～

**Comment by zbryikt** [comment]
@ipaaa @marygeek 我加了一頁 staff, check 一下是否 ok?
https://github.com/g0v/summit.g0v.tw/commit/66f2bfe2fdd614141559e265f262c79bc7c027e3
https://github.com/g0v/summit.g0v.tw/commit/25d4d6ec7d2dfb7dfdd3eaf81105311a9551d93b

已經先 deploy 了
