### ISSUE TITLE
add speaker avatar

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#39]
未上圖講者在這裡（待上圖）：
https://github.com/g0v/summit.g0v.tw/tree/master/app/assets/images/speaker

**Comment by yhsiang** [comment]
陳俊宏, 詹順貴, 朱雨其, 彭啟明, 鄧東波, 嚴婉玲, 鄭凱榕 done bca2441733f8e9422ed5fa4ef04ffe024916bd48
