### ISSUE TITLE
議程畫面第一層的人名語系沒有隨切換語系為 English 後變動

### ISSUE THREAD

**Issue by nchild** [g0v/summit2016#51]
只有點擊後跳出的簡介視窗會隨著語系切換變動，但是第一層（ http://summit.g0v.tw/en-US/schedule.html ）沒有，仍是抓到中文語系。

**Comment by yhsiang** [comment]
ya 本來是個dirty hack, 可能沒空改, 囧..要把東西做在jade裡面不適用schedule偷吃步
