### ISSUE TITLE
英文頁面上的「中文」按鈕連結錯誤

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#6]
應該是 summit.g0v.tw/zh-TW/index.html
現在是 summit.g0v.tw/index.html 預設英文瀏覽器就鬼打牆了 ><

**Comment by zbryikt** [comment]
fixed: 2a5507df198
在 app/layout/eng.jade 裏直接把中文連結指到 /zh-TW/index.html 來處理
