### ISSUE TITLE
broadcast page

### ISSUE THREAD

**Issue by yutin1987** [g0v/summit2016#68]
http://summit.g0v.tw/2016/live

**Comment by shelling** [comment]
@yutin1987 the live url is still to be determined?

**Comment by yutin1987** [comment]
yes, it will is a url list.

國際會議廳Youtube(華語)：
國際會議廳Youtube(英語)：https://www.youtube.com/user/g0vTW/live
國際會議廳Youtube(日語)：
國際會議廳Livehouse.in(華語)：https://livehouse.in/channel/g0v

第一會議室YouTube(華語)：
第一會議室YouTube(英語)：

第二會議室YouTube(華語)：
第二會議室YouTube(英語)：

**Comment by yhsiang** [comment]
直播頁面走鐘了，有請 @yutin1987！

**Comment by yhsiang** [comment]
我修好了直播頁面。 @yutin1987，這個 issue 是要把 session info 整合進去才打算 close ?
