### ISSUE TITLE
加 Unconf 資訊在中英文首頁

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2016#7]
g0v Summit 活動後來超展開變成有兩個：Conf 和 Unconf
目前只有 11/8 Conference 資訊，需要加第二天 Unconf ：

時間 11/9
地點 中央研究院資訊科學所

**Comment by shelling** [comment]
@ipaaa 目前在 index.html#about 有 unconf 了
也需要加到上面嗎？

**Comment by ipaaa** [comment]
下面我先加了說明
主圖那邊覺得還是要加一下 unconf 時地
但不知如何編排比較好又還要動圖...就先沒動
@shelling 要幫忙排一下嗎？
![screen shot 2014-09-22 at 8 39 19](https://cloud.githubusercontent.com/assets/2939042/4350558/2f8be212-41f1-11e4-9b65-93dd69bd146d.png)

**Comment by ipaaa** [comment]
中文我一時手滑先加了
英文是圖檔，我不會弄

**Comment by shelling** [comment]
用 png 下去直接改效果不太好，有 source 會比較好，看了一下 history 圖檔要請 @zbryikt 幫忙一下 XD

**Comment by marygeek** [comment]
因為英文版只是先趕著上線的單頁式網頁
其實我是要把中文網站改一套成英文搬過去
現在jade的架構我不熟
不太曉得要從何下手比較快能把中文站複製一份變成英站

2014-09-22 14:12 GMT+08:00 shelling notifications@github.com:

**Comment by zbryikt** [comment]
中英文版可以參考 g0v.tw 的做法:
https://github.com/g0v/g0v.tw/blob/master/app/partials/about.jade
第12行那邊透過判斷 lang 來決定接下來要 include 誰.

我想 summit 這邊概念會類似, 不過不見得是用 md, 比方說 schedule 我們預計要用 json, 我已經先弄了一個 schedule.json 出來了, 不過還沒整起來.. anyway 可以先從翻譯下手

**Comment by marygeek** [comment]
我覺得最簡單的做法就是乾脆用把英文資料都放在一頁
那就不用再弄一個英文site
只要用這個英文page
我已經改好英文版上方底圖把文字挖掉
改成純文字

zbryikt notifications@github.com 於 2014年9月22日 下午4:18 寫道：
