### ISSUE TITLE
增加 Summit Milestone 相關資訊

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#70]
Call for Paper：2016/01/12(二) 12:00 ~ 2016/02/22(一) 23:50 
國際早鳥票：2/15 - 3/20
社群貢獻票：2/15 - 3/20
一般票： 4/1 - 4/15

**Comment by jessy1092** [comment]
一般票： 4/1 - 4/15

**Comment by MrOrz** [comment]
「國際早鳥票」、「社群貢獻票」、「一般票」的正式英文譯名是什麼呢

**Comment by yhsiang** [comment]
@MrOrz 
Calling for Speakers: 徵求講者
Early Bird Program: 國際早鳥票
Contributor Program: 社群貢獻票
Normal Ticket: 一般票
