### ISSUE TITLE
更新確認講者

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#75]
資料待 @pm5 補上

**Comment by yhsiang** [comment]
![default](https://cloud.githubusercontent.com/assets/93509/13226436/5c6f407a-d9cc-11e5-8dc3-6be509dccc9e.png)

**Comment by clkao** [comment]
too many @deaves!

**Comment by deaves** [comment]
LOL!

**Comment by yhsiang** [comment]
講者：Shigeomi Shibata  
來自：Japan  Code for Japan, Code for Ibaraki  
講題：How to spread the civic tech movement to non-techie people?  
摘要："Code for Japan which is established on 2013 Nov. has now 33 official brigades and 20+ candidate groups. Growing speed is great I think but the member of groups mainly are techie guys. From the point of view for civic tech, we need more non-techie people. So I want to let you share our challenges and achievement and ask your thought. My name is Shigeomi Shibata, co-captain of code for Japan and a member of code for Ibaraki located on Mito-shi of Ibaraki prefecture."

講者：Jen Bramley  
來自：UK     mySociety  
講題：Powering civic tech reuse with EveryPolitician data  
摘要：Presenting the EveryPolitician project we will talk about the reasons why we're collecting all this open data and how it has already been used in different forms (for example: crowdsourcing data about the gender breakdown of every parliament in the world). We'll show real examples of the data being used to power civic technology sites in different countries - and hopefully you'll be inspired to create something yourself! (myself and my colleague Dave Whiteland would present together)

講者：Julia Kloiber 
來自：Germany    Open Knowledge Foundation Germany /
講題：Code for All   Code for All – Civic Tech around the World  
摘要："Coding for the public good is a global movement, from the US to Japan, from Mexico, to Pakistan developers are using their skills to hold government to account and to make life easier for all of us. Having built up the Code for Germany network, and had the opportunity to be a key part of the Code for All network, I want to take a look at what we've learned as a community so far. I want to take the audience on a journey through some of the best practices of the international Code for All community. On the basis of those examples I want to discuss what makes a good civic tech project. Why are some approaches better than others? What role does the user play in civic tech and how can we successful replicate projects?"

講者：Colin Megill
來自：US  pol.is 
講題：Pol.is in Taiwan: Bridging the gap between public discourse, consultation, and policy  
摘要：Pol.is is a new tool for gathering crowd sentiment in a way that preserves and respects minority opinions. It scales to any number of users, while preserving high dimensional, organic feedback. g0v and vTaiwan have used pol.is to foster productive discourse in the public sphere and influence policy related to Uber and AirBnB. We'll discuss pol.is as a technology and the case study of vTaiwan's successes with it.

講者：JK Suh
來自：Korea  WAGL
講題：The Korean General Election and VAAs: the case of "Ping"
摘要"Modern elections are becoming ever more sophisticated in terms of campaigners' ability to mine voter data and micro-tailor their messages to key demographics (see the Obama campaign's 'cave' of data scientists, e.g.: http://www.technologyreview.com/featuredstory/509026/how-obamas-team-used-big-data-to-rally-voters/ ). Voter Advice Applications, or VAAs, leverage similar techniques, but reverse the direction of the telescope: voters get a better understanding of candidates, not the other way around (see https://en.wikipedia.org/wiki/Voting_advice_application). VAAs have gained popularity in Canada, Germany, Britain, the Benelux countries and Switzerland, where around 10% of the population use a VAA (see http://www.euvox2014.eu/, http://www.democraticaudit.com/?p=12419, http://www.academia.edu/281395/Voting_Advice_Applications_in_Europe_The_State_of_the_Art for more examples from Europe). A basic VAA asks a series of questions that probe a user's political preference, then uses a distance measurement algorithm to visualize her position relative to parties and candidates that are standing in election. Ping, the first service of this kind to launch in East Asia, adds on to successes elsewhere in two ways: first, Ping provides local candidate information, beyond national party positions. Second, Ping crowd-sources its questions, so that users can ask district-specific questions to each candidate. The session will begin by reviewing the then-recent Korean General Election (held April 16) and place Ping in the broader context of the Korean Civic Hacking / Open Data community."

Keynote 講者：Felipe Heusser
來自："Chile "founder and former Director of Ciudadano Inteligente co-founded Rhinobird.tv Fellow at the Harvard Berkman Center for Internet and Society"
