### ISSUE TITLE
議程頁面

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#79]
![default](https://cloud.githubusercontent.com/assets/93509/13226398/2d0ae2c6-d9cc-11e5-8f27-8947c2b71cc9.png)

**Comment by MrOrz** [comment]
補一下 @jackycute 的 work in progress 傳送門：https://github.com/jackycute/summit.g0v.tw

**Comment by MrOrz** [comment]
WIP branch: https://github.com/g0v/summit.g0v.tw/tree/feature/schedule

**Comment by MrOrz** [comment]
Current progress in the WIP branch:
- [x] [Coscup-like](http://coscup.org/2015/zh-tw/program) Session lightbox & route handling
- [x] Filter function
- [x] Visual details: paddings, font size, etc.
- [ ] Affix (day1/day2 scroll spy & sticky filter)
- [ ] Style & HTML cleanup; better componentization for easier maintenance in the future

**Comment by MrOrz** [comment]
@yhsiang @othree  are there any recommended libraries for scroll spies or sticky menus in React? I'm going to implement the scroll interaction like the one in [Coscup program page](http://coscup.org/2015/zh-tw/program/#/).

If not, I'll build a HOC that registers a scroll event in window and do `getBoundingClientRect()` stuff inside, and wrap `day1`, `day2` and the entire schedule component with my HOC.

**Comment by ipaaa** [comment]
<img width="659" alt="screen shot 2016-03-25 at 20 18 16" src="https://cloud.githubusercontent.com/assets/2939042/14044200/a344a1a6-f2c8-11e5-887d-7e3a9194ecca.png">

應該用房號來filter，顯示出大標和 tagline
討論紀錄：https://g0v-tw.slack.com/archives/general/p1458625909000406 
https://g0v-tw.slack.com/archives/general/p1458908567000667
