### ISSUE TITLE
Prerender static html

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#82]
請參考 
https://github.com/COSCUP/coscup-schedule/blob/gh-pages/scripts/gen-static.js

產生靜態的頁面，利於 SEO

**Comment by MrOrz** [comment]
do we still need this when [json-ld is available in `<head>`](https://github.com/g0v/summit.g0v.tw/commit/c57f7a008ed9a7e4ffb433dbaec0acca80e9c94e)?

**Comment by MrOrz** [comment]
是說除了用 headless browser 來 prerender 之外，我想試試直接透過 HtmlWebpackPlugin 在 template 裡面拉 webpack compiled chunk 進來做 renderToString 之類的神秘做法。理論上因為 HtmlWebpackPlugin 的 html template 其實是 ejs，好像似乎可以直接在 `<% %>` 裡頭施展各種巫術——既然可以 [require og:image](https://github.com/MrOrz/summit.g0v.tw/commit/3460f6840f618480f3a08026ce8362c1b05a940b#diff-d13e648c450173d77b5e04da795274fdR12)，那應該也可以 require react 跟 require compiled bundle 之類的⋯⋯？

不過不一定做得出來，說不定我有想錯 QQ

**Comment by yhsiang** [comment]
有 json-ld 還是需要靜態頁面

**Comment by MrOrz** [comment]
got it, i am on it

**Comment by yhsiang** [comment]
其實有不少 static generator 的 plugin 可以試試，可能還要解決 html5 route 的問題

**Comment by MrOrz** [comment]
Work in process: https://github.com/MrOrz/summit.g0v.tw/tree/feature/static
