### ISSUE TITLE
broken navbar in safari

### ISSUE THREAD

**Issue by clkao** [g0v/summit2016#85]
reported by @fntsrlike++

![2016-02-27 1 17 45](https://cloud.githubusercontent.com/assets/69736/13360191/ee31fede-dcf2-11e5-8607-08ec1bc830ac.png)

**Comment by yhsiang** [comment]
c9c1541b46c069f580c33c36b1967188c209437b fixed

**Comment by fntsrlike** [comment]
![2016-02-27 1 45 47 1](https://cloud.githubusercontent.com/assets/2680724/13360365/dcfe8b86-dcf3-11e5-83c4-00ec65a00230.png)

@yhsiang ++
