### ISSUE TITLE
講題摘要 popup

### ISSUE THREAD

**Issue by yhsiang** [g0v/summit2016#89]
- [x] 支援 url
- [x] Popup modal

**Comment by billy3321** [comment]
https://github.com/g0v/summit.g0v.tw/pull/97

有兩個問題：
1. styles的classname好像不能包含「-」？
2. 不太懂popup model是什麼？

**Comment by yhsiang** [comment]
1. Please use camelCase
2. 請參考 http://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Comment by yhsiang** [comment]
支援 url 的意思是 要可以透過 /#/schedules/blahblah 連到這個 popup modal

**Comment by othree** [comment]
Any idea on how to define url, the `blahblah` part?

**Comment by yhsiang** [comment]
@othree I prefer use encodeURIComponent(Title of speech)

**Comment by othree** [comment]
Do we use bootstrap or implement our modal ?

**Comment by othree** [comment]
The problem of `encodeURIComponent(Title of speech)` is some name will become very long~

**Comment by yhsiang** [comment]
@othree or maybe `blahblah` use day_place_start-of-slot-time ?

like  `1_r1_10:00` `2_r0_13:00` ?

and I implement a draft version by @billy3321's lightbox.

any improvement welcome!
